.SILENT:

all: 
	cd 01; make
	cd 02; make
	cd 03; make
	cd 04; make
	cd 05; make
	cd 06; make
	cd 07; make
	cd 08; make
	cd 09; make
	cd 10; make

.PHONY: clean hiba

hiba:
	cd 01; make hiba
	cd 02; make hiba
	cd 03; make hiba
	cd 04; make hiba
	cd 05; make hiba
	cd 06; make hiba
	cd 07; make hiba
	cd 08; make hiba
	cd 09; make hiba
	cd 10; make hiba

clean:
	cd 01; make clean
	cd 02; make clean
	cd 03; make clean
	cd 04; make clean
	cd 05; make clean
	cd 06; make clean
	cd 07; make clean
	cd 08; make clean
	cd 09; make clean
	cd 10; make clean
